'use client';
import { useRef,useState } from 'react';
import { ArrowRight, Check, LoaderCircle } from 'lucide-react';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { projectTypes } from '@/data/profile';
export default function ContactForm(){
const [type,setType]=useState('');const [budget,setBudget]=useState('');const [state,setState]=useState('idle');const [error,setError]=useState('');const requestId=useRef('');
async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(state==='sending')return;if(!type){setError('Please select a project type.');return}const form=e.currentTarget;const data=new FormData(form);setState('sending');setError('');requestId.current ||=crypto.randomUUID();
try{const response=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:requestId.current,name:data.get('name'),email:data.get('email'),company:data.get('company')||'',message:data.get('message'),tools:data.get('tools')||'',projectType:type,budget,website:data.get('website')||''})});const result=await response.json() as {ok?:boolean;error?:string};if(!response.ok||!result.ok)throw new Error(result.error||'Unable to send your message.');setState('sent');form.reset();setType('');setBudget('');requestId.current=''}catch(e){setState('idle');setError(e instanceof Error?e.message:'Unable to connect. Please try again.')}
}
if(state==='sent')return <div className="form-success" role="status"><span className="success-icon"><Check/></span><h3>Message received.</h3><p>Thanks for sharing your idea. Let’s build something useful.</p><button className="text-button" onClick={()=>setState('idle')}>Send another message <ArrowRight size={16}/></button></div>;
return <form className="contact-form" onSubmit={submit}><div className="form-row"><label>Your name <span>*</span><input required name="name" autoComplete="name" maxLength={100} placeholder="Alex Morgan"/></label><label>Email address <span>*</span><input required name="email" type="email" autoComplete="email" maxLength={254} placeholder="alex@company.com"/></label></div><label>Company <small>(Optional)</small><input name="company" autoComplete="organization" maxLength={200} placeholder="Where you work"/></label><label>What do you want to automate? <span>*</span><textarea name="message" required maxLength={5000} rows={4} placeholder="Tell me about the process, the tools involved, and what you’d like to improve."/></label><label>Current tools <small>(Optional)</small><input name="tools" maxLength={500} placeholder="e.g. Google Sheets, Shopify, Slack"/></label><div className="form-row"><div className="field"><label id="type-label">Project type <span>*</span></label><Select value={type} onValueChange={setType}><SelectTrigger aria-labelledby="type-label" className="form-select"><SelectValue placeholder="Choose a project type"/></SelectTrigger><SelectContent position="popper" sideOffset={8} align="start" className="contact-select-content">{projectTypes.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div><div className="field"><label id="budget-label">Budget <small>(Optional)</small></label><Select value={budget} onValueChange={setBudget}><SelectTrigger aria-labelledby="budget-label" className="form-select"><SelectValue placeholder="Let’s discuss"/></SelectTrigger><SelectContent position="popper" sideOffset={8} align="start" className="contact-select-content">{['Under $500','$500–$1,500','$1,500–$5,000','$5,000+','Let’s discuss'].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div></div><div className="honeypot" aria-hidden="true"><label>Website<input name="website" tabIndex={-1} autoComplete="off"/></label></div>{error&&<p className="form-error" role="alert">{error}</p>}<button type="submit" className="button primary send-button" disabled={state==='sending'}>{state==='sending'?<>Sending <LoaderCircle className="spin" size={17}/></>:<>Send Message <ArrowRight size={17}/></>}</button><p className="form-note">Your details are used only to respond to your enquiry.</p></form>}
