'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, ArrowDown, ArrowRight, Workflow, Menu, X, GitBranch, Radio } from 'lucide-react';
import Network from './network';
import ContactForm from './contact-form';
import ProjectDetail from './project-detail';
import ScrollStory from './scroll-story';
import { profile } from '@/data/profile';
import { primarySkills,skillGroups } from '@/data/skills';
import { experience } from '@/data/experience';
import { projects, type Project } from '@/data/projects';
import { radyan,radyanWorkflows } from '@/data/radyan';
import { categories,changelog } from '@/data/changelog';
import { lab,labInterests } from '@/data/lab';
import { Braces, Sparkles, Layers, Network as NetworkIcon, Webhook, Cog, Database, FlaskConical, Check, Plus } from 'lucide-react';
export default function Portfolio(){
const [menu,setMenu]=useState(false); const [filter,setFilter]=useState('ALL'); const [detail,setDetail]=useState<Project|null>(null);
const filtered=changelog.filter(x=>filter==='ALL'||x.categories.includes(filter));
const skillIcons=[Workflow,Sparkles,GitBranch,Braces,Webhook,Cog,Layers,Database];
const steps=[['Understand','I first understand the existing business process.'],['Identify','I find repetitive or inefficient steps.'],['Design','I design the automation architecture.'],['Build','I create the workflow in n8n.'],['Integrate','I connect APIs, AI models and business tools.'],['Test','I test logic, edge cases and failures.'],['Deploy','I move the system into production.'],['Improve','I continue optimizing the workflow.']];

return <><a className="skip" href="#main">Skip to content</a><header className="header"><a href="#home" className="brand"><Workflow size={23}/><span>{profile.name}<span className="brand-dot">.</span></span></a><nav aria-label="Main navigation" className={menu?'nav open':'nav'}>{['Home','Work','Radyan','Skills','About','Contact'].map(x=><a onClick={()=>setMenu(false)} href={'#'+x.toLowerCase()} key={x}>{x}</a>)}</nav><a className="nav-cta" href="#contact">Let’s Work Together <ArrowUpRight size={15}/></a><button className="mobile-menu" aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
<main id="main"><section className="hero wrap" id="home"><div className="hero-top"><span className="eyebrow"><i/> AUTOMATION ENGINEER / N8N EXPERT</span><span className="edition">PERSONAL PORTFOLIO — 2026</span></div><div className="hero-grid"><div className="hero-copy"><h1>I Build Systems<br/>That Work<br/><span>Without You.</span></h1><p>I design production-ready n8n workflows, AI agents and API integrations that remove repetitive work and connect business operations.</p><div className="hero-actions"><a className="button primary" href="#work">Explore My Work <ArrowUpRight size={18}/></a><a className="text-button" href="#contact">Contact Me <ArrowRight size={17}/></a></div><a className="current-status" href="#radyan"><span className="status-dot"/> Automation Engineer at <strong>Radyan</strong><ArrowUpRight size={13}/></a></div><div className="network-shell"><div className="network-caption"><span><Radio size={12}/> AUTOMATION IN MOTION</span><span>01 — SYSTEM VIEW</span></div><Network/><div className="network-bottom"><span><i/> CONNECTED. AUTOMATED. INTELLIGENT.</span><span>HOVER TO EXPLORE ↗</span></div></div></div><div className="hero-foot"><span>BASED IN BANGLADESH <b>·</b> AVAILABLE FOR REMOTE PROJECTS</span><a href="#about">SCROLL TO EXPLORE <ArrowDown size={14}/></a></div></section>
<div className="tool-strip"><span>TURNING COMPLEXITY INTO FLOW</span><b>n8n</b><span>✳ OpenAI</span><span>⌘ API integrations</span><span>◈ Supabase</span><span>⤳ Intelligent workflows</span></div>
<section className="wrap section intro" id="about"><div className="section-label">01 / THE ENGINEER</div><div><h2>Hi, I’m Sabbit<span className="coral">.</span></h2><p className="large-copy">I turn repetitive work into<br/><span>automated systems.</span></p><p className="body-copy">I’m an Automation Engineer specializing in n8n, AI agents and API-driven workflows. I focus on understanding business processes, identifying repetitive work and designing reliable systems that automate those operations.</p><a className="text-button" href="#radyan">See what I’m building <ArrowUpRight size={18}/></a></div></section>
<section className="wrap section" id="radyan"><div className="section-head"><div><div className="section-label">02 / CURRENTLY BUILDING</div><h2>Inside my work at Radyan<span className="coral">.</span></h2></div><span className="status-badge"><span className="status-dot"/> ACTIVE & ONGOING</span></div><div className="radyan-feature"><div className="radyan-wordmark">R<span>Radyan</span><small>BUSINESS AUTOMATION / E-COMMERCE OPERATIONS</small></div><div className="radyan-content"><div className="tiny-label">MY CURRENT ROLE</div><h3>Automation Engineer</h3><p>{radyan.description}</p><p>{radyan.details}</p><div className="radyan-links"><button className="text-button" onClick={()=>setDetail(projects.find(p=>p.id==='radyan')||null)}>See What I’m Building <ArrowUpRight size={17}/></button><a href={radyan.url} target="_blank" rel="noreferrer" className="muted-link">radyanbd.com ↗</a></div></div></div><div className="subsection-heading"><h3>What I’m Building at Radyan</h3><span className="tiny-label">AN ONGOING AUTOMATION CASE STUDY</span></div>{radyanWorkflows.length?<div className="project-grid">{radyanWorkflows.map((p,i)=><ProjectCard key={p.id} project={p} index={i} onOpen={setDetail}/>)}</div>:<div className="documentation"><GitBranch size={21}/><div><h4>Work in progress. Documentation, too.</h4><p>I’m building and improving real operational workflows. Individual systems, architecture and approved screenshots will appear here as I document the work.</p></div><span className="tag">ONGOING</span></div>}<div className="metrics-row">{profile.metrics.some(x=>x.verified)?profile.metrics.filter(x=>x.verified).map(x=><div key={x.label}><strong>{x.value}</strong><span>{x.label}</span></div>):<><div><span className="tiny-label">WORKFLOWS & INTEGRATIONS</span><p>Real systems. Measured outcomes.</p></div><div className="metrics-note"><span className="status-dot"/> Tracking in progress<span>Verified results will be published as they’re measured.</span></div></>}</div></section>
<section className="wrap section" id="work"><div className="section-head"><div><div className="section-label">03 / SELECTED WORK</div><h2>Systems with a purpose<span className="coral">.</span></h2></div><p className="section-aside">My automation systems.<br/>The problems behind them.</p></div><div className="project-grid">{projects.map((p,i)=><ProjectCard key={p.id} project={p} index={i} onOpen={setDetail}/>)}</div></section>
<section className="wrap section" id="building"><div className="section-head"><div><div className="section-label">04 / THE BUILDING LOG</div><h2>What I’m Building<span className="coral">.</span></h2></div><span className="tiny-label">A LIVING ENGINEERING CHANGELOG</span></div><div className="filters" aria-label="Filter building log">{categories.map(x=><button key={x} aria-pressed={filter===x} className={filter===x?'selected':''} onClick={()=>setFilter(x)}>{x}</button>)}</div><div className="log" aria-live="polite">{filtered.length?filtered.map(x=><article className="log-row" key={x.id}><time>{x.date}</time><div><h3>{x.project}</h3><p>{x.update}</p><div className="tags">{x.technology.map(t=><span key={t}>{t}</span>)}</div></div><span className="status-badge"><span className="status-dot"/>{x.status}</span></article>):<div className="filter-empty"><GitBranch size={25}/><h3>No published updates yet.</h3><p>New {filter.toLowerCase()} updates will appear here as I document them.</p><button onClick={()=>setFilter('ALL')} className="text-button">View all updates <ArrowRight size={15}/></button></div>}</div></section>
<section className="story-section"><div className="wrap"><div className="section-label">05 / THE TRANSFORMATION</div><h2>From manual tasks<br/>to intelligent systems<span className="coral">.</span></h2><ScrollStory/></div></section>
<section className="wrap section" id="skills"><div className="section-head"><div><div className="section-label">06 / MY SKILLS</div><h2>Built on a connected skillset<span className="coral">.</span></h2></div><span className="section-aside">Architecture. Automation.<br/>Intelligence.</span></div><div className="skills-grid">{primarySkills.map((x,i)=>{const Icon=skillIcons[i];return <article className="skill-card" key={x.title}><Icon size={22}/><h3>{x.title}</h3><p>{x.description}</p><span className="skill-number">0{i+1}</span></article>})}</div><div className="toolkit"><div><div className="section-label">THE TOOLS BEHIND THE WORK</div><h2>Different tools.<br/>One working system.</h2><p className="body-copy">I connect the right tools for the process. Each integration becomes part of a bigger, more useful workflow.</p><div className="skill-groups">{skillGroups.map(x=><div key={x.title}><h4>{x.title}</h4><p>{x.tools.join(' · ')}</p></div>)}</div></div><div className="network-shell toolkit-network"><div className="network-caption"><span>TOOLS I WORK WITH</span><span>HOVER TO CONNECT ↗</span></div><Network toolkit/></div></div></section>
<section className="wrap section experience-section"><div className="section-label">07 / MY EXPERIENCE</div><h2>Building in the real world<span className="coral">.</span></h2>{experience.map(x=><article className="experience" key={x.company}><div><span className="status-dot"/> {x.period}<span className="experience-company">{x.company}</span></div><div><h3>{x.role}</h3><p className="body-copy">{x.description}</p><div className="tags">{x.skills.map(s=><span key={s}>{s}</span>)}</div><a href="#radyan" className="text-button">View Radyan Work <ArrowUpRight size={16}/></a></div><span className="tag">{x.status.toUpperCase()}</span></article>)}</section>
<section className="wrap section" id="process"><div className="section-head"><div><div className="section-label">08 / HOW I WORK</div><h2>A clear process.<br/>A reliable system.</h2></div><p className="section-aside">Understand the work first.<br/>Then make it work better.</p></div><div className="process-grid">{steps.map(([title,description],i)=><article key={title}><span className="process-index">0{i+1}</span><h3>{title}</h3><p>{description}</p>{i<7&&<ArrowRight size={15}/>}</article>)}</div></section>
<section className="wrap section" id="lab"><div className="section-head"><div><div className="section-label">09 / EXPLORATION</div><h2>Automation Lab<span className="coral">.</span></h2></div><FlaskConical size={32} className="coral"/></div><p className="body-copy">A space for experiments, prototypes and ideas that could become useful systems.</p>{lab.length?<div className="project-grid">{lab.map((p,i)=><ProjectCard key={p.id} project={p} index={i} onOpen={setDetail}/>)}</div>:<div className="lab-space"><div className="tiny-label">AREAS I’M EXPLORING</div><div className="lab-topics">{labInterests.map((x,i)=><span key={x}><span className="lab-index">{String(i+1).padStart(2,'0')}</span>{x}<Plus size={13}/></span>)}</div><p className="lab-note">Experiments will be published here with their actual status and findings.</p></div>}</section>
<section className="wrap section contact-section" id="contact"><div className="contact-copy"><div className="section-label">10 / LET’S CONNECT</div><h2>Let’s automate<br/><span className="coral">something useful.</span></h2><p className="body-copy">If you have a repetitive process, disconnected tools or a workflow that takes too much manual effort, I can help turn it into an automated system.</p><div className="contact-availability"><span className="status-dot"/> Available for remote projects<span>Based in {profile.location} · Working globally</span></div><div className="social-links">{profile.links.map(x=><a key={x.label} href={x.url} target="_blank" rel="noreferrer">{x.label} <ArrowUpRight size={17}/></a>)}{profile.email&&<a href={'mailto:'+profile.email}>Email <ArrowUpRight size={17}/></a>}</div></div><ContactForm/></section></main><footer className="wrap"><div className="footer-top"><a className="brand" href="#home"><Workflow size={25}/><span>{profile.name}<span className="brand-dot">.</span></span></a><p>Automation Engineer · n8n Expert<br/>AI Automation Specialist</p><span>Building systems that<br/>remove repetitive work.</span></div><div className="footer"><span>© 2026 {profile.name}</span><div className="footer-links">{profile.links.map(x=><a key={x.label} href={x.url} target="_blank" rel="noreferrer">{x.label} ↗</a>)}</div><a href="#home">Back to top ↑</a></div></footer><ProjectDetail project={detail} onClose={()=>setDetail(null)}/></>}
function ProjectCard({project:p,index,onOpen}:{project:Project;index:number;onOpen:(p:Project)=>void}){return <button className="project-card" onClick={()=>onOpen(p)}><div className="project-art"><div className="tiny-label">SYSTEM {String(index+1).padStart(2,'0')} / {p.company||'INDEPENDENT'}</div><div className="architecture-preview"><span><Webhook size={22}/>Trigger</span><i/><span className="architecture-core"><Workflow size={28}/>n8n</span><i/><span><Braces size={22}/>Integration</span><i/><span><Check size={22}/>Action</span></div><div className="project-art-bottom"><span>WORKFLOW ARCHITECTURE</span><span>CONCEPTUAL OVERVIEW</span></div></div><div className="project-info"><div className="project-title-line"><h3>{p.title}</h3><ArrowUpRight size={23}/></div><p>{p.summary}</p><div className="project-meta"><span>{p.company} / {p.role}</span><span className="status-badge"><span className="status-dot"/>{p.status}</span></div><div className="tags">{p.technologies.map(x=><span key={x}>{x}</span>)}</div></div></button>}
